#!/usr/bin/env bash
# PartyBoard — NextOS / Mali-450 GLES2 cross-configure (host -> aarch64, glibc 2.43).
# Reproduz a build aprovada. Reuso do SDL3 patcheado (sdl2 shim) do Dusklight.
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"
SDL_SRC=/home/felipe/ports_compile/dusklight-nextos/build/portmaster-aarch64-focal-sdl2shim/_deps/sdl-src
GLESV2="$ROOT/build/sysroot/lib/libGLESv2.so"

cmake -S "$ROOT" -B "$ROOT/build/nextos-gles2" -G Ninja \
  -DCMAKE_TOOLCHAIN_FILE="$ROOT/cmake/nextos-aarch64.toolchain.cmake" \
  -DCMAKE_BUILD_TYPE=Release \
  -DAURORA_GLES2=ON \
  -DAURORA_ENABLE_DVD=ON -DAURORA_ENABLE_CARD=ON -DAURORA_ENABLE_RMLUI=ON -DAURORA_ENABLE_GX=ON \
  -DAURORA_SDL3_PROVIDER=vendor -DAURORA_SDL3_LINKAGE=shared \
  -DFETCHCONTENT_SOURCE_DIR_SDL="$SDL_SRC" \
  -DAURORA_GLESV2_LIB="$GLESV2" \
  -DRust_CARGO_TARGET=aarch64-unknown-linux-gnu \
  -DCMAKE_DISABLE_FIND_PACKAGE_OpenGL=TRUE \
  -DCMAKE_DISABLE_FIND_PACKAGE_zstd=TRUE -DCMAKE_DISABLE_FIND_PACKAGE_ZSTD=TRUE \
  -DCMAKE_DISABLE_FIND_PACKAGE_PkgConfig=TRUE \
  -DSDL_SDL2_BACKEND=ON -DSDL_SDL2_BACKEND_JOYSTICK=ON -DSDL_GPU=OFF -DSDL_UNIX_CONSOLE_BUILD=ON \
  -DSDL_X11=OFF -DSDL_WAYLAND=OFF -DSDL_KMSDRM=OFF -DSDL_VULKAN=OFF -DSDL_RENDER_VULKAN=OFF \
  -DSDL_OPENGL=OFF -DSDL_OPENGLES=ON \
  -DSDL_PIPEWIRE=OFF -DSDL_PULSEAUDIO=OFF -DSDL_JACK=OFF -DSDL_SNDIO=OFF -DSDL_ALSA=OFF -DSDL_OSS=OFF -DSDL_DISKAUDIO=OFF \
  -DSDL_DBUS=OFF -DSDL_IBUS=OFF -DSDL_RPI=OFF -DSDL_ROCKCHIP=OFF \
  -DSDL_HIDAPI=OFF -DSDL_LIBUDEV=OFF -DSDL_HIDAPI_LIBUSB=OFF -DSDL_LIBURING=OFF \
  -DSDL_CAMERA=OFF -DSDL_DIALOG=OFF -DSDL_TRAY=OFF -DSDL_SENSOR=OFF -DSDL_POWER=OFF \
  -DSDL_DUMMYAUDIO=ON -DSDL_DUMMYVIDEO=ON -DSDL_OFFSCREEN=ON \
  -DSDL_RENDER=ON -DSDL_LOADSO=ON -DSDL_LIBC=ON -DSDL_SYSTEM_ICONV=ON
